/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PasteRouteImport } from './routes/paste'
import { Route as ResumeResumeIdRouteImport } from './routes/resume.$resumeId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PasteRoute = PasteRouteImport.update({
  id: '/paste',
  path: '/paste',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeResumeIdRoute = ResumeResumeIdRouteImport.update({
  id: '/resume/$resumeId',
  path: '/resume/$resumeId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/paste': typeof PasteRoute
  '/resume/$resumeId': typeof ResumeResumeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/paste': typeof PasteRoute
  '/resume/$resumeId': typeof ResumeResumeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/paste': typeof PasteRoute
  '/resume/$resumeId': typeof ResumeResumeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/paste' | '/resume/$resumeId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/paste' | '/resume/$resumeId'
  id: '__root__' | '/' | '/paste' | '/resume/$resumeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PasteRoute: typeof PasteRoute
  ResumeResumeIdRoute: typeof ResumeResumeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paste': {
      id: '/paste'
      path: '/paste'
      fullPath: '/paste'
      preLoaderRoute: typeof PasteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume/$resumeId': {
      id: '/resume/$resumeId'
      path: '/resume/$resumeId'
      fullPath: '/resume/$resumeId'
      preLoaderRoute: typeof ResumeResumeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PasteRoute: PasteRoute,
  ResumeResumeIdRoute: ResumeResumeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
